# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9d0ed81659500f0c859392fb0cac2745297b6f9255f1cb3305afa4dfa19022c61f721c57ab8126705935ed1a7fc8a767c9345dab17f60f4cfa37b5a7b8d3791

test:
  secret_key_base: 108117aa98aa71313633e3538d012f88292a83a8c2f6ae132806f992c438628f0be90608c8dccf5d8136f77d124bd519be92f564c4f6915efef0c74a1b1894b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
